[project]
name = "jupyterproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.4.4",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
]
